name: video_diary
description: "Video Diary - Your Personal Video Journal"
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  camera: ^0.11.2
  video_player: ^2.9.2
  file_selector: ^1.0.3
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.4
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_timezone: ^5.0.0
  video_thumbnail: ^0.5.3
  flutter_slidable: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8

  # Change App Package Name
  change_app_package_name: ^1.4.0

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.7

# Splash Screen Settings
flutter_native_splash:
  color: "#030303" # Arka plan rengi
  image: assets/logo/splash600.png # Splash görüntüsü
  android_12:
    image: assets/logo/splash1152.png # Android 12+ için splash görüntüsü
    color: "#030303" # Arka plan rengi

# App Icon Settings
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#030303"
  adaptive_icon_foreground: "assets/logo/logo_transparent.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo/